version: "3.9"  # Update with the latest stable version if needed

services:
  web:
    build: .  # Build the image from the current directory
    ports:
      - "5000:8051"  # Map container port 5000 to host port 5000
    volumes:
      - ./app:/app  # Mount local app directory to /app in container
    environment:
      - DATABASE_URL=mysql://db:3306/mydatabase  # Database connection details
    depends_on:
      - db

  db:
    image: mysql:8.0  # Use a specific MySQL image version
    environment:
      - MYSQL_ROOT_PASSWORD=password  # Set a strong password for root user
      - MYSQL_DATABASE=mydatabase  # Name of the database to create
    volumes:
      - db_data:/var/lib/mysql  # Persist database data (optional)

volumes:
  db_data:  # Define a named volume for database data
